
package uk.co.o2.soa.subscriberservice_2;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import uk.co.o2.soa.coredata_1.PaymentCategoryType;
import uk.co.o2.soa.coredata_1.SegmentType;
import uk.co.o2.soa.subscriberdata_2.BillingProfileType;
import uk.co.o2.soa.subscriberdata_2.GetBillProfile;
import uk.co.o2.soa.subscriberdata_2.GetBillProfileResponse;
import uk.co.o2.soa.subscriberdata_2.ProductListType;
import uk.co.o2.soa.subscriberdata_2.ServiceProviderDetailsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscriberPort", targetNamespace = "http://soa.o2.co.uk/subscriberservice_2")
@XmlSeeAlso({
    uk.co.o2.soa.coredata_1.ObjectFactory.class,
    uk.co.o2.soa.subscriberdata_2.ObjectFactory.class
})
public interface SubscriberPort {


    /**
     * 
     * @param subscriberID
     * @return
     *     returns uk.co.o2.soa.subscriberdata_2.SubscriberProfileType
     * @throws GetSubscriberProfileFault
     */
    @WebMethod
    @WebResult(name = "subscriberProfile", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
    @RequestWrapper(localName = "getSubscriberProfile", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberProfile")
    @ResponseWrapper(localName = "getSubscriberProfileResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberProfileResponse")
    public uk.co.o2.soa.subscriberdata_2.SubscriberProfileType getSubscriberProfile(
        @WebParam(name = "subscriberID", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String subscriberID)
        throws GetSubscriberProfileFault
    ;

    /**
     * 
     * @param subscriberID
     * @return
     *     returns uk.co.o2.soa.coredata_1.SegmentType
     * @throws GetSubscriberSegmentFault
     */
    @WebMethod
    @WebResult(name = "Segment", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
    @RequestWrapper(localName = "getSubscriberSegment", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberSegment")
    @ResponseWrapper(localName = "getSubscriberSegmentResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberSegmentResponse")
    public SegmentType getSubscriberSegment(
        @WebParam(name = "SubscriberID", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String subscriberID)
        throws GetSubscriberSegmentFault
    ;

    /**
     * 
     * @param subscriberID
     * @return
     *     returns uk.co.o2.soa.coredata_1.PaymentCategoryType
     * @throws GetSubscriberPaymentCategoryFault
     */
    @WebMethod
    @WebResult(name = "PaymentCategory", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
    @RequestWrapper(localName = "getSubscriberPaymentCategory", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberPaymentCategory")
    @ResponseWrapper(localName = "getSubscriberPaymentCategoryResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberPaymentCategoryResponse")
    public PaymentCategoryType getSubscriberPaymentCategory(
        @WebParam(name = "SubscriberID", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String subscriberID)
        throws GetSubscriberPaymentCategoryFault
    ;

    /**
     * 
     * @param subscriberID
     * @return
     *     returns java.lang.String
     * @throws GetSubscriberOperatorFault
     */
    @WebMethod
    @WebResult(name = "Operator", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
    @RequestWrapper(localName = "getSubscriberOperator", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberOperator")
    @ResponseWrapper(localName = "getSubscriberOperatorResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberOperatorResponse")
    public String getSubscriberOperator(
        @WebParam(name = "SubscriberID", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String subscriberID)
        throws GetSubscriberOperatorFault
    ;

    /**
     * 
     * @param subscriberID
     * @return
     *     returns java.lang.String
     * @throws GetSubscriberChannelFault
     */
    @WebMethod
    @WebResult(name = "channel", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
    @RequestWrapper(localName = "getSubscriberChannel", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberChannel")
    @ResponseWrapper(localName = "getSubscriberChannelResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberChannelResponse")
    public String getSubscriberChannel(
        @WebParam(name = "SubscriberID", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String subscriberID)
        throws GetSubscriberChannelFault
    ;

    /**
     * 
     * @param msisdn
     * @return
     *     returns uk.co.o2.soa.subscriberdata_2.BillingProfileType
     * @throws GetBillingSystemFault
     */
    @WebMethod
    @WebResult(name = "billingProfile", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
    @RequestWrapper(localName = "getBillingSystem", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetBillingSystem")
    @ResponseWrapper(localName = "getBillingSystemResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetBillingSystemResponse")
    public BillingProfileType getBillingSystem(
        @WebParam(name = "msisdn", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String msisdn)
        throws GetBillingSystemFault
    ;

    /**
     * 
     * @param billingProfile
     * @param subscriberProfile
     * @param msisdn
     * @throws GetSubscriberAndBillingSystemFault
     */
    @WebMethod
    @RequestWrapper(localName = "getSubscriberAndBillingSystem", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberAndBillingSystem")
    @ResponseWrapper(localName = "getSubscriberAndBillingSystemResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSubscriberAndBillingSystemResponse")
    public void getSubscriberAndBillingSystem(
        @WebParam(name = "msisdn", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String msisdn,
        @WebParam(name = "subscriberProfile", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", mode = WebParam.Mode.OUT)
        Holder<uk.co.o2.soa.coredata_1.SubscriberProfileType> subscriberProfile,
        @WebParam(name = "billingProfile", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", mode = WebParam.Mode.OUT)
        Holder<BillingProfileType> billingProfile)
        throws GetSubscriberAndBillingSystemFault
    ;

    /**
     * 
     * @param getBillProfile
     * @return
     *     returns uk.co.o2.soa.subscriberdata_2.GetBillProfileResponse
     * @throws GetBillProfileFault
     */
    @WebMethod
    @WebResult(name = "getBillProfileResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", partName = "getBillProfileResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetBillProfileResponse getBillProfile(
        @WebParam(name = "getBillProfile", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", partName = "getBillProfile")
        GetBillProfile getBillProfile)
        throws GetBillProfileFault
    ;

    /**
     * 
     * @param msisdn
     * @param productList
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws GetChargingCategoryFault
     */
    @WebMethod
    @WebResult(name = "chargingCategory", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
    @RequestWrapper(localName = "getChargingCategory", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetChargingCategory")
    @ResponseWrapper(localName = "getChargingCategoryResponse", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetChargingCategoryResponse")
    public List<String> getChargingCategory(
        @WebParam(name = "msisdn", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String msisdn,
        @WebParam(name = "productList", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        ProductListType productList)
        throws GetChargingCategoryFault
    ;

    /**
     * 
     * @param serviceProviderId
     * @return
     *     returns uk.co.o2.soa.subscriberdata_2.ServiceProviderDetailsType
     * @throws GetSPIDDetails1Fault
     */
    @WebMethod(operationName = "getSPIDDetails_1")
    @WebResult(name = "serviceProviderDetails", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
    @RequestWrapper(localName = "getSPIDDetails_1", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSPIDDetails1RequestType")
    @ResponseWrapper(localName = "getSPIDDetails_1Response", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2", className = "uk.co.o2.soa.subscriberdata_2.GetSPIDDetails1ResponseType")
    public ServiceProviderDetailsType getSPIDDetails1(
        @WebParam(name = "serviceProviderId", targetNamespace = "http://soa.o2.co.uk/subscriberdata_2")
        String serviceProviderId)
        throws GetSPIDDetails1Fault
    ;

}
